server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 120.24.210.204:1111 #配置Nacos地址

management:
  endpoints:
    web:
      exposure:
        include: '*'




